# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "47145414153916a0e175cdfe6d9b93b9"
application_url = "https://collection-layout-builder.vercel.app"
embedded = true
name = "collection-layout-builder"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://collection-layout-builder.vercel.app/auth/callback",
  "https://collection-layout-builder.vercel.app/auth/shopify/callback",
  "https://collection-layout-builder.vercel.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
